# wrangler.toml
name = "gemini-proxy-panel"
main = "src/index.ts"
compatibility_date = "2025-03-27"
compatibility_flags = ["nodejs_compat"]

[assets]
binding = "ASSETS"
directory = "./public"

[observability]
enabled = true

[[kv_namespaces]]
binding = "GEMINI_KEYS_KV"
id = "5f9d6a3155d0479fbfc62f214ea46557"

[[kv_namespaces]]
binding = "WORKER_CONFIG_KV"
id = "5f9d6a3155d0479fbfc62f214ea46557"

